### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by TimMensch** [1000ch/grunt-image#17]
I can't npm install, and Travis CI is experiencing the same build error.

Any fix in the pipe?

**Comment by 1000ch** [comment]
@TimMensch Sorry for broken. It might be fixed, so would you try again?

**Comment by TimMensch** [comment]
It builds now, thanks for the quick fix!

Though there's another issue: After the task runs it says "Fatal error: Bad Argument". If I delete these from the options section, it works:

          zopflipng: true,
          pngcrush: true,

If I use EITHER of those, I get the error. For now, I'm just disabling both. They all worked fine on 0.9.6. I'm on Windows 7 in MSYS/MinGW, by the way.

Thanks again.

**Comment by 1000ch** [comment]
Sorry again, This problem is also fixed now at `v1.0.2`.

**Comment by TimMensch** [comment]
Thanks; sorry for the delay in my reply, but I did end up grabbing the latest version and testing it, and it did work correctly.

Thanks again for the fast response!
