### ISSUE TITLE
GIFs are not being optmized

### ISSUE THREAD

**Issue by MagazineduWebdesign** [1000ch/grunt-image#23]
GIF files aren't optimized with this config: grunt-image 1.5.1 and gifsicle 5.0.1. With tour expertise, could you tell me if I did something wrong?
![capture](https://cloud.githubusercontent.com/assets/10801706/16178328/108afb42-3645-11e6-9cb0-934e0d4b18bc.PNG)

**Comment by 1000ch** [comment]
@MagazineduWebdesign 
Still getting error with `v2.0.0`?
If so, could you upload thats GIF?
