### ISSUE TITLE
Not installing dependencies

### ISSUE THREAD

**Issue by Erseni** [1000ch/grunt-image#27]
`npm install --no-bin-links `
is not installing all the required image optimizing dependencies

`Warning: spawn /vagrant/node_modules/jpeg-recompress-bin/vendor/jpeg-recompress ENOENT Use --force to continue.
Warning: spawn /vagrant/node_modules/optipng-bin/vendor/optipng ENOENT Use --force to continue.
`

I have to install them manually to get them working.
With version 1.5.2 it was working but after upgrade to 2.x it is broken.

**Comment by 1000ch** [comment]
Why do you use `--no-bin-links` option?
